branches:
  only:
    - master

os:
  - linux

dist: bionic

language: node_js

node_js:
  - "12"

before_install:
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y libopenjp2-tools
  - sudo apt-get install --no-install-recommends -y rpm
  - sudo apt-get install --no-install-recommends -y bsdtar
  - npm i -g npm
  - npm i -g yarn

install:
  - yarn

script:
  - yarn generate-icons
  - yarn build

cache:
  yarn: true