skip_commits:
  message: /(\[skip ci\]|\[skip appveyor\])/

branches:
  only:
    - master

environment:
  GH_TOKEN:
    secure: HHISy+sGq57hKlEtc0o7esy0gVWqL+0LZjmvVQa38W66OfqEs/LBhJhtI6MIC66y

image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\Yarn'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm i -g npm
  - npm i -g yarn
  - yarn

build_script:
  - yarn generate-icons
  - yarn build

test: off